### PR TITLE
fix: Achievement Cards

### LINKED ISSUE #245: Bug: Achievement Card Sizing
grafik

### PR DESCRIPTION
**Pull request by Laennart**
closes #245

### CODE REVIEW

**Review by Y4nnikH — COMMENTED** [review]
looks great now!

File: src/pages/profile/user/sub_pages/achievements/components/achievementCard.tsx [hunk 1]
```diff
@@ -41,14 +60,26 @@ const AchievementCard: React.FC<Props> = ({
         <Col style={{ marginLeft: "20px", overflow: "hidden" }}>
           <Text style={{ fontSize: 25 }}>{achievement.title}</Text>
           <br />
-          <div style={{ width: "230px" }}>{achievement.description}</div>
+          {achievement.description.length > 50 && (
+            <Tooltip title={achievement.description}>{description}</Tooltip>
+          )}
+          {achievement.description.length <= 50 && description}
```
Comment (Gamer92000) [inline src/pages/profile/user/sub_pages/achievements/components/achievementCard.tsx:66]:
```suggestion
          {achievement.description.length > 50 ? (
            <Tooltip title={achievement.description}>{description}</Tooltip>
          ) :  (description)}
```

**Review by Gamer92000 — CHANGES_REQUESTED** [review]
